Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: Sz4889212  # 填写你的数据库密码
  Host: 114.215.139.30:3306
  DBName: gin-test
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Database2:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: Sz4889212  # 填写你的数据库密码
  Host: 114.215.139.30:3306
  DBName: test
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Username: root
  Password: 4889212
  Host: 114.215.139.30
  Port: 6379
  DB: 1