Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: ******  # 填写你的数据库密码
  Host: *********
  DBName: gin-test
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Database2:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: ********  # 填写你的数据库密码
  Host: ********
  DBName: test
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Username: root
  Password: ********
  Host: ********
  Port: 6379
  DB: 1
